project:
  type: book

book:
  title: "Data7 Reproducible Research with GitHub and RStudio Workshop Companion Book"
  author: "Greg Chism"
  date: "8/22/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - create-compendium.qmd
    - manage-as-package.qmd
    - reproduce-distill-paper.qmd
    - references.qmd
    
  repo-url: https://github.com/Gchism94/Data7-rrtools-repro-research

bibliography: references.bib

format:
  html:
    theme: cosmo



