project:
  type: book

book:
  title: "Data7 Reproducible Research with GitHub and RStudio Book"
  author: "Greg Chism"
  cover-image: cover.png
  repo-url: https://github.com/Gchism94/Data7-rrtools-repro-research
  chapters:
    - index.qmd
    - intro.qmd
    - create-compendium.qmd
    - manage-as-package.qmd
    - reproduce-distill-paper.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-copy: true



